// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/admin/applicant-data" | "/admin/billing" | "/admin/companies" | "/admin/companies/[id]" | "/admin/dashboard" | "/admin/login" | "/admin/question-bank" | "/admin/satisfaction" | "/admin/security" | "/admin/suspension" | "/client/applicants" | "/client/applicants/[id]" | "/client/billing" | "/client/login" | "/client/plan" | "/client/suspension" | "/client/templates" | "/interview/[slug]" | "/interview/[slug]/cancelled" | "/interview/[slug]/complete" | "/interview/[slug]/form" | "/interview/[slug]/prepare" | "/interview/[slug]/session" | "/interview/[slug]/uploading" | "/interview/[slug]/verify"
type AppRouteHandlerRoutes = "/api/health"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/client"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/applicant-data": {}
  "/admin/billing": {}
  "/admin/companies": {}
  "/admin/companies/[id]": { "id": string; }
  "/admin/dashboard": {}
  "/admin/login": {}
  "/admin/question-bank": {}
  "/admin/satisfaction": {}
  "/admin/security": {}
  "/admin/suspension": {}
  "/api/health": {}
  "/client": {}
  "/client/applicants": {}
  "/client/applicants/[id]": { "id": string; }
  "/client/billing": {}
  "/client/login": {}
  "/client/plan": {}
  "/client/suspension": {}
  "/client/templates": {}
  "/interview/[slug]": { "slug": string; }
  "/interview/[slug]/cancelled": { "slug": string; }
  "/interview/[slug]/complete": { "slug": string; }
  "/interview/[slug]/form": { "slug": string; }
  "/interview/[slug]/prepare": { "slug": string; }
  "/interview/[slug]/session": { "slug": string; }
  "/interview/[slug]/uploading": { "slug": string; }
  "/interview/[slug]/verify": { "slug": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/client": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
