// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/admin/(dashboard)/applicant-data/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/applicant-data">> = Specific
  const handler = {} as typeof import("../../../app/admin/(dashboard)/applicant-data/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/(dashboard)/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/billing">> = Specific
  const handler = {} as typeof import("../../../app/admin/(dashboard)/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/(dashboard)/companies/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/companies/[id]">> = Specific
  const handler = {} as typeof import("../../../app/admin/(dashboard)/companies/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/(dashboard)/companies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/companies">> = Specific
  const handler = {} as typeof import("../../../app/admin/(dashboard)/companies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/admin/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/(dashboard)/question-bank/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/question-bank">> = Specific
  const handler = {} as typeof import("../../../app/admin/(dashboard)/question-bank/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/(dashboard)/satisfaction/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/satisfaction">> = Specific
  const handler = {} as typeof import("../../../app/admin/(dashboard)/satisfaction/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/(dashboard)/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/security">> = Specific
  const handler = {} as typeof import("../../../app/admin/(dashboard)/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/(dashboard)/suspension/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/suspension">> = Specific
  const handler = {} as typeof import("../../../app/admin/(dashboard)/suspension/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../../app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/client/(dashboard)/applicants/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/applicants/[id]">> = Specific
  const handler = {} as typeof import("../../../app/client/(dashboard)/applicants/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/client/(dashboard)/applicants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/applicants">> = Specific
  const handler = {} as typeof import("../../../app/client/(dashboard)/applicants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/client/(dashboard)/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/billing">> = Specific
  const handler = {} as typeof import("../../../app/client/(dashboard)/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/client/(dashboard)/plan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/plan">> = Specific
  const handler = {} as typeof import("../../../app/client/(dashboard)/plan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/client/(dashboard)/suspension/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/suspension">> = Specific
  const handler = {} as typeof import("../../../app/client/(dashboard)/suspension/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/client/(dashboard)/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/templates">> = Specific
  const handler = {} as typeof import("../../../app/client/(dashboard)/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/client/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/login">> = Specific
  const handler = {} as typeof import("../../../app/client/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/interview/[slug]/cancelled/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/interview/[slug]/cancelled">> = Specific
  const handler = {} as typeof import("../../../app/interview/[slug]/cancelled/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/interview/[slug]/complete/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/interview/[slug]/complete">> = Specific
  const handler = {} as typeof import("../../../app/interview/[slug]/complete/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/interview/[slug]/form/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/interview/[slug]/form">> = Specific
  const handler = {} as typeof import("../../../app/interview/[slug]/form/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/interview/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/interview/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/interview/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/interview/[slug]/prepare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/interview/[slug]/prepare">> = Specific
  const handler = {} as typeof import("../../../app/interview/[slug]/prepare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/interview/[slug]/session/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/interview/[slug]/session">> = Specific
  const handler = {} as typeof import("../../../app/interview/[slug]/session/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/interview/[slug]/uploading/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/interview/[slug]/uploading">> = Specific
  const handler = {} as typeof import("../../../app/interview/[slug]/uploading/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/interview/[slug]/verify/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/interview/[slug]/verify">> = Specific
  const handler = {} as typeof import("../../../app/interview/[slug]/verify/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/admin/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/client/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/client">> = Specific
  const handler = {} as typeof import("../../../app/client/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
